// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

import { envConfig } from '../config/env';

const env = envConfig();

export const supabase = createClient(
    env.SUPABASE_URL,
    env.SUPABASE_PUBLISHABLE_KEY,
    {
        auth: {
            storage: localStorage,
            persistSession: true,
            autoRefreshToken: true,
        },
    }
);
